# Copyright (C) 2025 Advanced Micro Devices, Inc.

services:
  tgi-service:
    image: ghcr.io/huggingface/text-generation-inference:3.0.0-rocm
    container_name: tgi-service
    ports:
      - "${AGENTQNA_TGI_SERVICE_PORT:-18008}:80"
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    environment:
      no_proxy: ${no_proxy:-}
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      TGI_LLM_ENDPOINT: "http://${HOST_IP}:${AGENTQNA_TGI_SERVICE_PORT:-18008}"
      HF_TOKEN: ${AGENTQNA_HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      WILM_USE_TRITON_FLASH_ATTENTION: 0
      PYTORCH_JIT: 0
    shm_size: 128G
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    ipc: host
    command: "--model-id ${AGENTQNA_LLM_MODEL_ID} --max-input-length 4096 --max-total-tokens 8192 --dtype float16 --trust-remote-code"
    restart: unless-stopped
    networks:
      - rocm_default

  worker-rag-agent:
    image: ${REGISTRY:-opea}/agent:${TAG:-latest}
    container_name: rag-agent-endpoint
    volumes:
      - "${TOOLSET_PATH}:/home/user/tools/"
    ports:
      - "${WORKER_RAG_AGENT_PORT:-9095}:9095"
    ipc: host
    environment:
      ip_address: ${HOST_IP}
      strategy: rag_agent_llama
      with_memory: false
      recursion_limit: ${recursion_limit_worker}
      llm_engine: tgi
      HF_TOKEN: ${AGENTQNA_HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${AGENTQNA_BACKEND_SERVICE_ENDPOINT}
      model: ${AGENTQNA_LLM_MODEL_ID}
      temperature: ${temperature}
      max_new_tokens: ${max_new_tokens}
      stream: false
      tools: /home/user/tools/worker_agent_tools.yaml
      require_human_feedback: false
      RETRIEVAL_TOOL_URL: ${RETRIEVAL_TOOL_URL}
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      LANGCHAIN_PROJECT: "opea-worker-agent-service"
      port: 9095
    restart: unless-stopped
    networks:
      - rocm_default

  worker-sql-agent:
    image: ${REGISTRY:-opea}/agent:${TAG:-latest}
    container_name: sql-agent-endpoint
    volumes:
      - "${WORKDIR}/tests/Chinook_Sqlite.sqlite:/home/user/chinook-db/Chinook_Sqlite.sqlite:rw"
    ports:
      - "${WORKER_SQL_AGENT_PORT:-9096}:9096"
    ipc: host
    environment:
      ip_address: ${HOST_IP}
      strategy: sql_agent_llama
      with_memory: false
      db_name: ${db_name}
      db_path: ${db_path}
      use_hints: false
      recursion_limit: ${recursion_limit_worker}
      llm_engine: vllm
      HF_TOKEN: ${AGENTQNA_HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${AGENTQNA_BACKEND_SERVICE_ENDPOINT}
      model: ${AGENTQNA_LLM_MODEL_ID}
      temperature: ${temperature}
      max_new_tokens: ${max_new_tokens}
      stream: false
      require_human_feedback: false
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      port: 9096
    restart: unless-stopped
    networks:
      - rocm_default

  supervisor-react-agent:
    image: ${REGISTRY:-opea}/agent:${TAG:-latest}
    container_name: react-agent-endpoint
    depends_on:
      - worker-rag-agent
    volumes:
      - "${TOOLSET_PATH}:/home/user/tools/"
    ports:
      - "${SUPERVISOR_REACT_AGENT_PORT:-9090}:9090"
    ipc: host
    environment:
      ip_address: ${HOST_IP}
      strategy: react_llama
      with_memory: true
      recursion_limit: ${recursion_limit_supervisor}
      llm_engine: tgi
      HF_TOKEN: ${AGENTQNA_HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${AGENTQNA_BACKEND_SERVICE_ENDPOINT}
      model: ${AGENTQNA_LLM_MODEL_ID}
      temperature: ${temperature}
      max_new_tokens: ${max_new_tokens}
      stream: true
      tools: /home/user/tools/supervisor_agent_tools.yaml
      require_human_feedback: false
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      LANGCHAIN_PROJECT: "opea-supervisor-agent-service"
      CRAG_SERVER: ${CRAG_SERVER}
      WORKER_AGENT_URL: ${WORKER_AGENT_URL}
      SQL_AGENT_URL: ${SQL_AGENT_URL}
      port: 9090
    restart: unless-stopped
    networks:
      - rocm_default

networks:
  rocm_default:
    driver: bridge
