global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.17.0.1:8080']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # ChatQnA Backend Server
  - job_name: 'chatqna-backend'
    static_configs:
      - targets: ['chatqna-backend-server:8888']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # TGI Service (LLM)
  - job_name: 'tgi-service'
    static_configs:
      - targets: ['chatqna-tgi-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # TEI Embedding Service
  - job_name: 'tei-embedding'
    static_configs:
      - targets: ['chatqna-tei-embedding-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # TEI Reranking Service
  - job_name: 'tei-reranking'
    static_configs:
      - targets: ['chatqna-tei-reranking-service:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Retriever Service
  - job_name: 'retriever'
    static_configs:
      - targets: ['chatqna-retriever:7000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Data Prep Service
  - job_name: 'dataprep'
    static_configs:
      - targets: ['chatqna-dataprep-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis Vector Database
  - job_name: 'redis'
    static_configs:
      - targets: ['chatqna-redis-vector-db:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s 
